### ISSUE TITLE
trailing white space

### ISSUE THREAD

**Issue by AzureViolin** [AzureViolin/intelligent_scissors_5421spring2018#3]
@onlytailei can you avoid introducing trailing white spaces? Currently newline definitely introduce trailing white space, among other cases.

Your editor should support that function, usually. If you are using vim then `%s/\s\+\$//g` will do. Otherwise, IDLE have that capability as well. 

I rendered trailing white spaces in vim so that you can see:
![screenshot from 2018-02-18 11 25 52](https://user-images.githubusercontent.com/1617352/36351225-9bc5af70-149e-11e8-8846-75bf7d18669d.png)

**Comment by onlytailei** [comment]
No problem. My vimrc file has this highlight before. I will configure it on my laptop.
