### ISSUE TITLE
ipynb v.s. json

### ISSUE THREAD

**Issue by AzureViolin** [AzureViolin/intelligent_scissors_5421spring2018#4]
what is .ipynb used for?

And, since it seems like it's just json, why not use json directly? @onlytailei

**Comment by onlytailei** [comment]
This is an ipython notebook, an interactive python environment. I use it to test all the python functions. Actually, it should be ignored in git.

**Comment by AzureViolin** [comment]
sounds interesting. I'll remove it and add it to .gitignore. Maybe you can show me how it works when we do the demonstration :)
